### ISSUE TITLE
Every # Weeks

### ISSUE THREAD

**Issue by tgourley** [jamesstill/ScheduleWidget#35]
I am wondering if this more of an "addition" than an issue.  I would like to schedule something every # number of weeks.  Such as "Every other Friday".

Is this possible?  Or would this be something that would have to be added in?

**Comment by tgourley** [comment]
I found my own answer.
```c#
var event = new Event()
                {
                    ID = 1,
                    Title = "Paycheck",
                    FrequencyTypeOptions = FrequencyTypeEnum.Weekly,
                    RepeatInterval = 2,
                    DaysOfWeekOptions = DayOfWeekEnum.Fri,
                    StartDateTime = new DateTime(2016, 4, 22)
                });
```

The **RepeatInterval** property can skip any number of **FrequencyType**.  So by setting this to 2, it will then skip every other week.

**Comment by jamesstill** [comment]
I'm so lame. Just now looking at this issue. :) Thank you for sharing!
